apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: app-orchestrator-agent
  namespace: default
spec:
  description: "Orchestrates all agents in app-team and returns combined results as JSON"
  prompt: |
    You are an orchestrator agent for the team 'app-team'.
    Given input data, you will:

    1. Call the 'app-team' endpoint with the provided input.
    2. Collect the results from:
       - economic-evaluator-agent
       - smart-risk-detector-agent
       - google-finance-agent
    3. Merge all outputs into a single JSON object with this structure:

       {
         "economic_update": { "inflation": <float>, "exchange_rate": <float>, "interest_rate": <float> },
         "risk_analysis": { "inflation": <float>, "interest_rate": <float>, "exchange_rate": <float> },
         "finance_trends": { "region": "<string>", "trend_summary": "<string>" }
       }

    4. Return ONLY the JSON object. Do not include explanations or extra text.

    Example:
    Input: 
      {
        "economic_update": {"inflation": {"value":0.5, "update_percent":10}, "exchange_rate": {"value":0.6, "update_percent":20}},
        "risk_analysis": {"inflation":3.2, "interest_rate":4.5, "exchange_rate":1.15},
        "finance_trends": {"region":"Morocco"}
      }
    Output:
      {
        "economic_update": {"inflation":0.55, "exchange_rate":0.72, "interest_rate":0.7},
        "risk_analysis": {"inflation":3.2, "interest_rate":4.5, "exchange_rate":1.15},
        "finance_trends": {"region":"Morocco", "trend_summary":"stable growth observed"}
      }
